# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8cc200288757f02a13ce7d3fa5e77d47fb79a762281cffe80002b050173a509c96e7666c367d079ee6ae551edcc319e7ea0822894eeb899ef9e2c1314700834

test:
  secret_key_base: 045fd863002b6b6e935fbbe9978f335b2f29267c662ff875db0f3122f4158bfe66e0d5f0bdee9b591ae4cd2f5f9a3840f983c77e2ac99ccad350f6bc975a21f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
